cd ../..
export PYTHONPATH=/home/erick/MotionProjs/ASE_MODS/lib:$LD_LIBRARY_PATH

#python ase/output_recorder/video_stacker.py --video_files_paths /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/gt.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/par_three.avi --sync_times 10.7999 8.93333 --orientation vertical
#python ase/output_recorder/video_cutter.py --video_files_paths /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/sync_max.mp4 --del_times 4.5 28.0

#python ase/output_recorder/stack_frame.py --video_files_paths /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/gt.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/par_one.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/par_three.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/par_five.avi --sync_times 5.0 4.5 4.5 4.5 --orientation vertical --basename par

#python ase/output_recorder/stack_frame.py --video_files_paths /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/gt.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/par_one.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/par_three.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/par_five.avi --sync_times 10.5 8.2 8.5 9.2 --orientation vertical --basename par

#python ase/output_recorder/stack_frame.py --video_files_paths /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/gt.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/par_one.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/par_three.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/par_five.avi --sync_times 15.2 12.5 12.5 12.8 --orientation vertical --basename par

#python ase/output_recorder/stack_frame.py --video_files_paths /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/gt.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/par_one.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/par_three.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/par_five.avi --sync_times 22.6 16.5 17.0 17.5 --orientation vertical --basename par

#python ase/output_recorder/stack_frame.py --video_files_paths /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/gt.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/questsim_one.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/questsim_three.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/questsim_five.avi --sync_times 5.0 4.5 4.5 4.5 --orientation vertical --basename questsim

#python ase/output_recorder/stack_frame.py --video_files_paths /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/gt.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/questsim_one.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/questsim_three.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/questsim_five.avi --sync_times 10.5 10.0 9.9 10.2 --orientation vertical --basename questsim

#python ase/output_recorder/stack_frame.py --video_files_paths /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/gt.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/questsim_one.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/questsim_three.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/questsim_five.avi --sync_times 15.2 15.0 13.8 14.5 --orientation vertical --basename questsim

#python ase/output_recorder/stack_frame.py --video_files_paths /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/gt.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/questsim_one.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/questsim_three.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/questsim_five.avi --sync_times 22.6 19.0 22.0 20.8 --orientation vertical --basename questsim

#python ase/output_recorder/stack_frame.py --video_files_paths /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/gt.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/72par_one.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/72par_three.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/72par_five.avi --sync_times 5.0 4.5 4.5 4.5 --orientation vertical --basename 72par

#python ase/output_recorder/stack_frame.py --video_files_paths /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/gt.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/72par_one.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/72par_three.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/72par_five.avi --sync_times 10.5 10.0 14.5 14.5 --orientation vertical --basename 72par

#python ase/output_recorder/stack_frame.py --video_files_paths /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/gt.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/72par_one.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/72par_three.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/72par_five.avi --sync_times 15.2 22.5 21.5 21.9 --orientation vertical --basename 72par

python ase/output_recorder/stack_frame.py --video_files_paths /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/gt.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/72par_one.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/72par_three.avi /home/erick/Videos/exp_vids/different_number_of_trackers/019_Relaxed_3_mirror_x_1_0/72par_five.avi --sync_times 22.6 26.5 28.5 28.5 --orientation vertical --basename 72par



