args:
  algo_name: ''
  cfg_env: ase/data/cfg/humanoid_imitation_vrh.yaml
  cfg_train: ase/data/cfg/train/rlg/common_ppo_humanoid.yaml
  checkpoint: Base
  compute_device_id: 0
  device: cuda
  device_id: 0
  episode_length: 0
  experiment: Base
  flex: false
  graphics_device_id: 0
  headless: true
  horizon_length: -1
  horovod: false
  llc_checkpoint: ''
  logdir: logs/
  max_iterations: 0
  metadata: false
  minibatch_size: -1
  motion_file: ase/data/motions/dataset_cmu_07_01_all_heights.yaml
  num_envs: 0
  num_threads: 0
  output_path: output/
  physics_engine: &id001 !!python/object/new:isaacgym._bindings.linux-x86_64.gym_37.SimType
    state: 0
  physx: false
  pipeline: gpu
  play: false
  randomize: false
  real_time: false
  resume: 0
  rl_device: cuda:0
  seed: null
  sim_device: cuda:0
  sim_device_type: cuda
  slices: 0
  subscenes: 0
  task: HumanoidImitationTrack
  task_type: Python
  test: false
  torch_deterministic: false
  train: true
  use_gpu: true
  use_gpu_pipeline: true
cfg:
  args: !!python/object:argparse.Namespace
    algo_name: ''
    cfg_env: ase/data/cfg/humanoid_imitation_vrh.yaml
    cfg_train: ase/data/cfg/train/rlg/common_ppo_humanoid.yaml
    checkpoint: Base
    compute_device_id: 0
    device: cuda
    device_id: 0
    episode_length: 0
    experiment: Base
    flex: false
    graphics_device_id: 0
    headless: true
    horizon_length: -1
    horovod: false
    llc_checkpoint: ''
    logdir: logs/
    max_iterations: 0
    metadata: false
    minibatch_size: -1
    motion_file: ase/data/motions/dataset_cmu_07_01_all_heights.yaml
    num_envs: 0
    num_threads: 0
    output_path: output/
    physics_engine: *id001
    physx: false
    pipeline: gpu
    play: false
    randomize: false
    real_time: false
    resume: 0
    rl_device: cuda:0
    seed: null
    sim_device: cuda:0
    sim_device_type: cuda
    slices: 0
    subscenes: 0
    task: HumanoidImitationTrack
    task_type: Python
    test: false
    torch_deterministic: false
    train: true
    use_gpu: true
    use_gpu_pipeline: true
  env:
    asset:
      assetFileName:
      - mjcf/amp_humanoid_vrh_140.xml
      - mjcf/amp_humanoid_vrh_152.xml
      - mjcf/amp_humanoid_vrh_160.xml
      - mjcf/amp_humanoid_vrh_168.xml
      - mjcf/amp_humanoid_vrh_180.xml
      - mjcf/amp_humanoid_vrh_185.xml
      - mjcf/amp_humanoid_vrh_193.xml
      - mjcf/amp_humanoid_vrh_207.xml
      - mjcf/amp_humanoid_vrh_212.xml
      - mjcf/amp_humanoid_vrh_220.xml
      assetHeight:
      - 1.4
      - 1.52
      - 1.6
      - 1.68
      - 1.8
      - 1.85
      - 1.93
      - 2.07
      - 2.12
      - 2.2
      assetRoot: ase/data/assets
      jointsIndices:
      - 0
      - 1
      - 2
      - 4
      - 5
      - 6
      - 8
      - 9
      - 10
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      jointsNames:
      - pelvis
      - torso
      - head
      - right_upper_arm
      - right_lower_arm
      - right_hand
      - left_upper_arm
      - left_lower_arm
      - left_hand
      - right_thigh
      - right_shin
      - right_foot
      - left_thigh
      - left_shin
      - left_foot
      mixImitHeights: true
      multipleHeights: true
      trackBodies:
      - headset
      - right_controller
      - left_controller
      trackIndices:
      - 3
      - 7
      - 11
    contactBodies:
    - right_foot
    - left_foot
    controlFrequencyInv: 1
    enableDebugVis: false
    enableEarlyTermination: true
    envSpacing: 5
    episodeLength: 300
    hybridInitProb: 0.5
    imitParams:
      joint_friction: 0.1
      k_dof_pos: 40.0
      k_dof_vel: 0.3
      k_force: 0.01
      k_pos: 6.0
      k_vel: 2.0
      num_steps_track_info: 6
      rtBodyInputOrder:
      - headset
      - left_controller
      - right_controller
      w_dof_pos: 0.4
      w_dof_vel: 0.1
      w_force: 0.2
      w_pos: 0.2
      w_vel: 0.1
    isFlagrun: false
    keyBodies:
    - right_hand
    - left_hand
    - right_foot
    - left_foot
    localRootObs: false
    motion_file: ase/data/motions/dataset_cmu_07_01_all_heights.yaml
    numEnvs: 8
    pdControl: false
    plane:
      dynamicFriction: 1.0
      restitution: 0.0
      staticFriction: 1.0
    play: false
    powerScale: 1.0
    real_time: false
    stateInit: Hybrid
    terminationHeight: 0.15
    test: false
  headless: true
  name: HumanoidImitationTrack
  seed: -1
  sim:
    flex:
      num_inner_iterations: 10
      warm_start: 0.25
    physx:
      bounce_threshold_velocity: 0.2
      contact_offset: 0.02
      default_buffer_size_multiplier: 10.0
      max_depenetration_velocity: 10.0
      num_position_iterations: 4
      num_threads: 4
      num_velocity_iterations: 0
      rest_offset: 0.0
      solver_type: 1
    substeps: 2
  task:
    randomize: false
cfg_train:
  params:
    algo:
      name: common
    config:
      checkpoint: Base
      clip_value: false
      critic_coef: 1
      e_clip: 0.2
      entropy_coef: 0.0
      env_name: rlgpu
      full_experiment_name: HumanoidImitation_21-04-15-10-44
      gamma: 0.97
      grad_norm: 1.0
      horizon_length: 15
      learning_rate: 1e-4
      lr_schedule: constant
      max_epochs: 100000
      mini_epochs: 5
      minibatch_size: 15
      mixed_precision: false
      multi_gpu: false
      name: HumanoidImitation
      normalize_advantage: true
      normalize_input: true
      normalize_value: true
      num_actors: 8
      ppo: true
      print_stats: true
      reward_shaper:
        scale_value: 1
      save_best_after: 1000
      save_frequency: 100
      score_to_win: 20000
      tau: 0.95
      train_dir: output/
      truncate_grads: true
    load_checkpoint: false
    model:
      name: continuous_a2c_logstd
    network:
      mlp:
        activation: tanh
        d2rl: false
        initializer:
          name: default
        regularizer:
          name: None
        units:
        - 400
        - 300
        - 200
      name: common
      separate: true
      space:
        continuous:
          fixed_sigma: true
          learn_sigma: false
          mu_activation: None
          mu_init:
            name: default
          sigma_activation: None
          sigma_init:
            name: const_initializer
            val: 0
    seed: 8418
